### ISSUE TITLE
Last modified time not showing up correctly

### ISSUE THREAD

**Issue by kdheepak** [tlienart/Xranklin.jl#114]
With this footer:

```
<div class="page-foot">
    <a href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a> {{ fill author }}. {{isnotpage /tag/*}}Last modified: {{ fill fd_mtime }}.{{end}}
    Website built with <a href="https://github.com/tlienart/Franklin.jl">Franklin.jl</a> and the <a href="https://julialang.org">Julia programming language</a>.
</div>
```

I get this:

![Screen Shot 2022-03-03 at 6 54 23 PM](https://user-images.githubusercontent.com/1813121/156684195-40da7dad-f81b-4622-b8b5-2f9b6bdb7d34.png)

**Comment by tlienart** [comment]
Right, in Xranklin this is meant to be handled by a hfun (there will be a dedicated one) in the meantime just use

```
function hfun_last_modified()
    mtime = locvar("fd_mtime")
    isnothing(mtime) && return ""
    last_modified = unix2datetime(mtime)
    date_str = Dates.format(last_modified, "U d, yyyy") # or whatever format you prefer
    return "Last modified: $date_str"
end
```

and put `{{last_modified}}` in the foot.

**Comment by tlienart** [comment]
@kdheepak I've just added this, you can now use `{{last_modification_date}}` and it will show for instance `March 2, 2022`. 

You can select the date format by changing `date_format` in your `config.md`. The default is `"U d, yyyy"`. You can also define your own locale if you want via `date_days, date_shortdays, date_months, date_shortmonths`. 

This is now used in the Xranklin docs if you check the bottom of a page.

**Comment by kdheepak** [comment]
This works great! Thanks!

![Screen Shot 2022-03-08 at 1 50 35 PM](https://user-images.githubusercontent.com/1813121/157322767-92bb8e06-a4a9-4d3b-b622-733d29b5e4a0.png)
