### ISSUE TITLE
Feature request: Add source_commit_hash hfun

### ISSUE THREAD

**Issue by kdheepak** [tlienart/Xranklin.jl#117]
For most of my blog posts on my personal blog I have something like the following that gets autogenerated:

```
<a target="_blank" href="https://github.com/kdheepak/blog/blob/7a9a6f5abcb8b6b1b052a39474f7b6b0cdd463ee/src/posts/43-sveltekit-starter.md">Link to source</a>
```

I generate the hash using the following:

```
git log -n 1 --pretty=format:%H -- ${filename}
```

where filename is the name of the source markdown file for which I want to include this link in the generated output.

It'd be nice to have this built in as a feature, like `hfun_source_commit_hash` for each file or something like that that I can include as part of the template. That way I can click on the link and get to the github repo with the exact changes for that build.

**Comment by tlienart** [comment]
Just to check are you asking how to do a hfun that does this (should be easy) or you already have one and suggest it be included as a core hfun?

**Comment by kdheepak** [comment]
I was going to write one and haven't written one yet, but I should be able to figure it out. In the case of keeping the core light, I'll close this issue.

**Comment by tlienart** [comment]
The quickest way to do it should be to run your exact command in a pipeline pass the result to an iobuffer, extract the relevant hash and return it.

For the path to the current file, you can use `getlvar(:_relative_path)` or `cur_lc().rpath` which is the relative path to the file from the website folder.
