### ISSUE TITLE
Tag-specific RSS?

### ISSUE THREAD

**Issue by kescobo** [tlienart/Xranklin.jl#141]
Whether this is a separate feed per-tag, or some other way of filtering the main feed by tag, some (documented) way to submit a Xranklin blog to julia-bloggers would be very useful. From slack conversation:

> a reasonable PR would be to explicitly specify a list of list of pages to include in the RSS feed(s).
> for the tag stuff, you would specify in config.md something like `rss_feeds = (some logic producing a list of list of pages)`
> the logic could then e.g. be based on tags (or whatever else).
> this variable would then be read by `generate_rss` [here](https://github.com/tlienart/Xranklin.jl/blob/0a2349dc79944002c1b090b5ee453d88a4eaa313/src/context/rss.jl#L11-L61). Recovering rss_feeds from gc with `rss_feeds = getvar(gc, :rss_feeds, Vector{Vector{String}}())`
> if `rss_feeds` is empty (default) the current behaviour would be applied. Otherwise the logic would be applied for each list in `rss_feeds`.
> a pr like this would require change [here](https://github.com/tlienart/Xranklin.jl/blob/fc68fda0e308625c81101469c1bd7e114ca1e678/src/context/default_context.jl#L60) (add `rss_feeds` var following the blueprint of other stuff)
> in `generate_rss` as per description above there might need to be some additional reasoning for the naming of feeds etc but that should be it. 

I can take a look tomorrow at what this involve, but I'd def. be fine with just whatever logic is used in Franklin itself.

**Comment by tlienart** [comment]
the within RSS feed categorisation can be done with the `<category>` item which can be modified by specifying `rss_category = "..."` on a page (it will impact appear here: https://github.com/tlienart/FranklinTemplates.jl/blob/cdb2dab40dad9c3f0d75d255eda44180fbdbeef1/src/templates/common/_rss/item.xml#L49-L51 and the expected syntax is https://www.rssboard.org/rss-draft-1#element-channel-category) 

That being said, I don't know how well `<category>` is processed by RSS feed readers (RSS is pretty messy from my (in)experience), and I can see that places like Wordpress and Substack have a per-category or per-tag feed. It's also there in Franklin where one has `/tag/tag_name/feed.xml`. So it would make sense to port that logic to  Franklin in any case. The suggestion made above is for general filtering which might not make a ton of sense, the Franklin logic is just for tags which is probably sufficient; the logic is here https://github.com/tlienart/Franklin.jl/blob/1b9d57137e38e3b34357b67b9b5288e4d3c100de/src/manager/rss_generator.jl#L100-L123

@kescobo I can't guarantee how quickly I'll get to this but it'll be done eventually.
