### ISSUE TITLE
Post-specific environments

### ISSUE THREAD

**Issue by kescobo** [tlienart/Xranklin.jl#144]
I'm most interested in this for `literate` notebooks, but it would be nice to be able to have post-specific `Project.toml` / `Manifest.toml`. Duplicate of https://github.com/tlienart/Franklin.jl/issues/528.

The primary use-case for me is to be able to have pinned versions of packages / reproducible manifests attached to individual posts.

**Comment by tlienart** [comment]
You can already do this though?

- have your post folder
- create a subfolder `my-post-number-26`
- have a file `index.md` in there with the post content
- have toml files in there
- have the main file `index.md` actively load these files doing `Pkg.activate(...)` etc in a code block. 

Note that if you do it, you have to do that everywhere, as otherwise the next blog post will use that environment (either that or you need to re-activate the general environment at the end of the blog post).

**Comment by kescobo** [comment]
>meaning for instance that if you have one post that uses ThePackage@v0.5 and another ThePackage@v0.6, activating/deactivating will not be enough to guarantee that each page uses respectively 0.5 and 0.6

Interesting. I guess the only way around this would be to start a new julia instance for each post? That would get messy with live-updating, I guess.

But otherwise, I think this would be really nice.

**Comment by kescobo** [comment]
If I really desperately need equisite control over the environment, it's ~~easy~~ straightforward enough (I think, haven't tried) to just use Literate.jl/Weave.jl directly to generate HTML in a separate process, then drop it in.

**Comment by kescobo** [comment]
Yeah, I definitely think that makes sense. In principle, I can imagine situations where you'd want to have multiple different environments, but that seems like a tiny minority of cases, and probably too fiddly to try to support it. This is the kind of thing where a user should probably write their own code to deal with it.

**Comment by tlienart** [comment]
Right exactly, a user can always just use Pkg as they see fit.

Ok I'll try to figure this one out, thanks for the suggestion, I'll probably reach out to you again to test it 😅

**Comment by tlienart** [comment]
This is over a year ago and I'd totally understand if you've moved on to other stuff but the feature is now with an example in #197; if you do get a chance to try, lmk and thanks for the feature request!

**Comment by kescobo** [comment]
Oh, sorry - my ability to work on web stuff really took a nose-dive over the last year! The examples look great, I'll be happy to test this out!
