### ISSUE TITLE
Shutting down the server activates the global environment for no reason

### ISSUE THREAD

**Issue by giordano** [tlienart/Xranklin.jl#169]
```
[ Info: Listening on: 127.0.0.1:8000
✓ LiveServer listening on http://localhost:8000/ ...
  (use CTRL+C to shut down)
^C
⋮ shutting down LiveServer… [ Info: Server on 127.0.0.1:8000 closing
✓

[ Info: 📓 serializing global context...
[ Info: ... [global context] ✓
[ Info: 📓 serializing 10 local context...
[ Info: ... [lc of tutorials/index.md] ✓
[ Info: ... [lc of 404.md] ✓
[ Info: ... [lc of tutorials/preferences.md] ✓
[ Info: ... [lc of news/2022/07/dagger_julius_benchmark.md] ✓
[ Info: ... [lc of news/index.md] ✓
[ Info: ... [lc of index.md] ✓
[ Info: ... [lc of resources/index.md] ✓
[ Info: 📓 keep copy of config.md...
[ Info: 📓 keep copy of utils.jl...
[ Info: 💡 serializing done (δt = 0.8s)

[ Info: 🗑️ cleaning up all objects
[ Info: 💡 cleaning up done (δt = 1ms)

  Activating project at `~/.julia/environments/v1.8`
```
I don't see why shutting down the server should change the environment at all. I want to keep using the environment that was active before starting the server, which may ***not*** be the global one.

**Comment by tlienart** [comment]
Thanks for the feedback @giordano ; the intent is indeed exactly what you point out. It should be reasonably easy to fix, will try to do that in the next couple of days

**Comment by tlienart** [comment]
The main fix in https://github.com/tlienart/Xranklin.jl/commit/1e0fe858a74a2e06f77e84bb3455c2c071002cb8 is that at the end of a `serve` instead of just `Pkg.activate()` it activates the previous `Pkg.project().path` called before the build unless this hasn't changed.

This should remove the issue mentioned above but let me know if that's not the case.
