### ISSUE TITLE
Lists may start immediately after a header

### ISSUE THREAD

**Issue by giordano** [tlienart/Xranklin.jl#174]
Probably another parser bug, [spotted](https://github.com/JuliaParallel/juliaparallel.github.io/commit/f1d346f078f6b460306dc3968ab50f00cb9d900c) together with #172: in
```
# Header
* item 1
* item 2
```
the line "item 1" is rendered in a paragraph outside of the bullet list.  While I think it'd be nicer to have a blank line after the header, I don't think that's required by Markdown, for example GitHub renders the "item 1" line above in the bullet list as expected:

> # Header
> * item 1
> * item 2

**Comment by tlienart** [comment]
Hmm yes, that was deliberate but might indeed be too strict (note that the parser does not attempt to strictly follow a markdown guideline, this is potentially controversial but it makes some stuff far far easier; in that specific instance though it's probably unnecessarily strict).

**Comment by tlienart** [comment]
this should be fixed now, will tag a patch release on FP side; thanks again for the recent feedback :+1:

**Comment by giordano** [comment]
Thanks!
