### ISSUE TITLE
Help with deployment?

### ISSUE THREAD

**Issue by kescobo** [tlienart/Xranklin.jl#252]
Finally got around to re-building BioJulia website, but we're having some issues with deployment. On https://biojulia.github.io/, it's visible, but not styled correctly. On https://biojulia.dev/, it's a 404. 

I added you to [the repo](https://github.com/BioJulia/biojulia.github.io) (and sorry to keep pulling on your time!)

**Comment by kescobo** [comment]
Nevermind, I fixed it - was a github pages setting (that shouldn't have had to change from the previous version, but :shrug: )

**Comment by tlienart** [comment]
Awesome
