### ISSUE TITLE
Activating an environment in a REPL Pkg block changes the environment in the source REPL

### ISSUE THREAD

**Issue by gdalle** [tlienart/Xranklin.jl#262]
Same problem as I had on Franklin, when I activate an environment on a website page it changes the environment in the REPL where I launched the website

**Comment by gdalle** [comment]
Edit: apparently it's only a problem when the website crashes

**Comment by tlienart** [comment]
yes I can see that happening, we keep track of the initial environment though so it should be possible to put the main logic in a big try-finally with the finally returning everything to how it was before.

**Comment by gdalle** [comment]
As you can see I've switched ModernJuliaWorkflows to Xranklin, so expect more issues in the near future ;)
