### ISSUE TITLE
Naming REPL blocks

### ISSUE THREAD

**Issue by gdalle** [tlienart/Xranklin.jl#264]
I just realize that the brand new help, pkg and shell modes in REPL blocks do not accept names (they don't show up as `evaluting cell myname` during website build).

As a side note, is it possible to execute these blocks in the same context as plain code blocks? Eg defining a function in a code block and playing with it in a REPL block?

**Comment by tlienart** [comment]
```
julia> s = """
       ```!foo
       x = 5
       ```

       ```>bar
       y = x + 2
       ```
       """
"```!foo\nx = 5\n```\n\n```>bar\ny = x + 2\n```\n"

julia> println(html(s))
[ Info:   ⏯️  evaluating cell foo...
[ Info:   ⏯️  evaluating cell bar_1...
<pre><code class="julia">x = 5</code></pre>
<pre><code class="julia-repl"><span class="sgr32"><span class="sgr1">julia&gt;</span></span> y = x + 2
7
</code></pre>
```

isn't that what you want?

**Comment by gdalle** [comment]
Right, maybe I screwed up or missed them in the crowd. Closing for now
