### ISSUE TITLE
#hide and #mock don't work in REPL mode

### ISSUE THREAD

**Issue by gdalle** [tlienart/Xranklin.jl#268]
at least I think so

**Comment by tlienart** [comment]
yes that's true, do you find it preferable to have that inside repl code block rather than have a hidden plain block before it?

````
```!
#hideall
x = 5
y = 7
```

```>
z = x+y
```
````

**Comment by gdalle** [comment]
I'll do it with a standard code block, no worries

**Comment by adrhill** [comment]
@tlienart We have run into some use-cases where it would be preferable to do

````md
```>
do_stuff("here")  # mock
do_stuff(folderpath("here"))  # hide
```
````

Our current workarounds in MoJuWo have confused some users.

**Comment by gdalle** [comment]
We could just split the REPL blocks and insert a hidden code block in between?

**Comment by adrhill** [comment]
It looks like `#hideall` also doesn't work: 

<img width="731" alt="image" src="https://github.com/user-attachments/assets/214d55bf-8e71-43a9-bfb5-ca206c43fb3f">


What we want:
````md
```>pkgtemplates
using PkgTemplates
t = Template(user="myuser", interactive=false); # mock
t = Template(dir=Utils.path(:site), user="myuser", interactive=false); # hide
t("MyAwesomePackage")
```
````

The workaround that would work but look very odd:

````md
```>pkgtemplates1
using PkgTemplates
t = Template(user="myuser", interactive=false);  
```

```!pkgtemplates2
#hideall
t = Template(dir=Utils.path(:site), user="myuser", interactive=false);
```

```>pkgtemplates3
t("MyAwesomePackage")
```
````
