### ISSUE TITLE
Missing line break in Pkg REPL mode

### ISSUE THREAD

**Issue by gdalle** [tlienart/Xranklin.jl#271]
![image](https://github.com/tlienart/Xranklin.jl/assets/22795598/e3939e5b-7cb2-453c-9bc0-fb2b5366c246)

**Comment by tlienart** [comment]
there's a counter increment missing here

https://github.com/tlienart/Xranklin.jl/blob/c92dc3e04d7b03ba8cfc31c124907bd8dc8d4c8c/src/convert/markdown/rules/code.jl#L447
