### ISSUE TITLE
Handle multiple separate post list

### ISSUE THREAD

**Issue by luraess** [tlienart/Xranklin.jl#273]
@tlienart - It would be handy to be able to have the blog-post mechanism working independently in different pages of a Xranklin website.

In the following, assume I have a News and another Event section and I would like to be able to "drag and drop" `.md` files in one or another to have them listed as new entry in their respective website pages.

WIP here https://github.com/Unil-SGC/unil-sgc.github.io/blob/62a9541e5f87a2e32507d629f7a22261fd4f35a0/utils.jl#L69-L115

For now, I duplicated the `hfun_list_posts` function to have a second `hfun_list_events`, specifying the folder `dir` from where to get the posts from. 2 things:
1. Ideally, it would be elegant and handy to be able to specify the `dir` when calling a generic `list_posts` function from the markdown index file as e.g. `{{list_posts posts}}` and `{{list_posts events}}` (or even better, retrieve the `post` or `event` name from the dir name itself that contains the `index.md` file)
2. There is an issue with current duplicate function as the `hfun_taglist` function complains and would need a change to be able to accept `dir`, or multiple `hfun_list_xx` funtions 

Any thoughts or hints welcome

**Comment by tlienart** [comment]
> Ideally, it would be elegant and handy to be able to specify the dir when calling a generic list_posts function from the markdown index file as e.g. `{{list_posts posts}}` and `{{list_posts events}}` (or even better, retrieve the post or event name from the dir name itself that contains the index.md file)

you can do this already can't you? or do you hit a bug when you try to do this? 

if in `utils.jl` you have

```
def hfun_foo(p)
    # ...
end
```

`p` here is assumed to be a vector of string arguments that you pass so `{{foo a b c}}` --> `hfun_foo("a", "b", "c")`. So you could indeed pass a directory name to achieve exactly `{{list_posts posts}}`. 

The one about retrieving `post` or `event` from the dir name itself can be done via the localcontext object:

```
def hfun_foo()
    relative_path_to_caller_page = get_lc().rpath  # e.g. foo/bar/index.md 
    # ... here you can do dir stuff
end
```

I'm not sure I understand your second point, could you give a bit more details?

**Comment by luraess** [comment]
Thanks for your input. I am a bit confused about your `def` in code snippet. 

Indeed, passing the folder as argument to `hfun` in `utils.jl` works. But the issue is then in 
```julia
function hfun_taglist()
    return hfun_list_posts(getlvar(:tag_name))
end
```
as this would then also need to get the `dir` var passed along.

Also, it seems not to know what to do with `get_lc().rpath` in Julia.

**Comment by luraess** [comment]
I gave a try to this https://github.com/Unil-SGC/unil-sgc.github.io/blob/2d7c06d5eba3b4e104ff6afad6dcf8654c11ef72/utils.jl#L49-L63 which works as it can parse e.g. `{{list_posts events}}` or `{{list_posts posts}}`. However, I have still the issue on how to make it compatible for https://github.com/Unil-SGC/unil-sgc.github.io/blob/2d7c06d5eba3b4e104ff6afad6dcf8654c11ef72/utils.jl#L36-L38 (previously done by https://github.com/Unil-SGC/unil-sgc.github.io/blob/2d7c06d5eba3b4e104ff6afad6dcf8654c11ef72/utils.jl#L64)

**Comment by tlienart** [comment]
Hahaha I did too much python for work recently sorry... 

The `cur_lc()` returns the current context (from the page that calls the hfun), this has a field `rpath` which indicates the path to that caller page. You seemed to indicate in your initial post that you needed this?

I'll try to take a look at what you did tmrw morning!

**Comment by luraess** [comment]
ok cool, now using
```julia
dir = splitpath(cur_lc().rpath)[end-1]
```
indeed returns the folder where I have my posts and it seems to work.

What still fails is 
1. having
```julia
function hfun_taglist()
    return hfun_list_posts(getlvar(:tag_name))
end
```
as it complains about not finding the tag defined in the `md` files within the non "posts" folder

2. The style of the listing in the secondary post-like page is not good.

**Comment by tlienart** [comment]
Will take a look now

**Comment by tlienart** [comment]
so if you put a `@show dirname(cur_lc().rpath)` in `hfun_list_posts` you'll see that it calls it with `tags/event`; I need to check something in Xranklin as the _reason_ why this is happening may be that `cur_lc` does not get reset properly after adding tags; I'll check.

In any case if you do this:

```julia
function hfun_list_posts(t::String)
    dir = dirname(cur_lc().rpath)

    startswith(dir, "tags") && return ""
   # then rest of your function as you had it
``` 

things look like they work fine.

**Comment by luraess** [comment]
Cool, now it indeed works adding `dir = dirname(cur_lc().rpath); startswith(dir, "tags") && return ""`.

However, there is a minor styling issue (applying CSS?) between "original" posts folder and "new" event folder:

Posts (News) - how it should be:
<img width="896" alt="Screenshot 2023-11-09 at 16 09 49" src="https://github.com/tlienart/Xranklin.jl/assets/61313342/df415b27-7544-448a-8f12-8ff69f9a3f83">

Events - the issue:
<img width="896" alt="Screenshot 2023-11-09 at 16 09 58" src="https://github.com/tlienart/Xranklin.jl/assets/61313342/bea47409-b695-4263-9341-81518e47d618">

EDIT:
If I rename `posts` to `news` (no it should work as it picks folder name), then I also get the "wrong" styling. Is there something hardcoded about `posts` somewhere?

**Comment by luraess** [comment]
The remaining style issue comes from the fact the `/posts` is hard-coded in `_layout/head.html`: https://github.com/Unil-SGC/unil-sgc.github.io/blob/35f1511b0360aeb041d0e068487b40490f1871c9/_layout/head.html#L78-L87.

Would there be way to make the "post" folder name a variable as in utils?

Following change makes it work https://github.com/Unil-SGC/unil-sgc.github.io/commit/f1cc36c3a726d3df457824088c7f15c8024f07a0 however, it would require to list "post" pages there manually ...

**Comment by tlienart** [comment]
`ispage` accepts multiple inputs so just add `news/*` after posts `{{ispage posts/* news/*}}`

**Comment by luraess** [comment]
Yes, this works and what's currently implemented. I was just wondering if there would be a more generic way to achieve this. A minor thing though.

**Comment by tlienart** [comment]
sorry not sure I understand, could you maybe write how you would like the logic to look like in a code sketch? would you like something like `{{ispage (some logic here)}}` ?

**Comment by luraess** [comment]
Yes. Ideally we could programmatically retrieve all folders with `posts` logic `(some logic here)` to apply the style. Unsure though it is feasible.

**Comment by tlienart** [comment]
I might be a bit dense but I still don't get what you're trying to achieve in an ideal scenario. Would you mind giving me a step by step description of what you'd like?

The thing is that logic in ispage (to describe a set of pages that we want something to apply to) is doable via estrings `e"Julia here"`. But you seem to describe something else which would be doable with hfun.

Basically hfun have virtually no limits so if you can write Julia code that does what you want, then you can write a hfun that does it. Now it might be _convenient_ to leverage some convenience stuff like ispage etc, this is what I'm trying to get from your description.

**Comment by luraess** [comment]
Thanks for your patience and sorry for my poor explanation. I guess it is partly due to the fact I do not fully grasp the machine the way `{{ispage ...}}` works in the `_layout/head. html`.

First, the solution of manually adding the folders that contain blog posts after `ispage` works. In my specific case, having `{{ispage posts/* news/*}}` does the job as I have currently `posts` and `news` as folders where I add `md` files that should be listed as blog-post entries in the website. 

The only "remaining" open question I thus have is to know if there would be a way to not have to specify manually the names of the blog-post hosting folders (here `posts` and `news`) in the `{{ispage posts/* news/*}}` call? In other words, would there be a way that `_layout/head.html` could figure out is called from a blog post entry (being in the `posts` or `news` folder) to apply the correct layout.

**Comment by luraess** [comment]
> so if you put a `@show dirname(cur_lc().rpath)` in `hfun_list_posts` you'll see that it calls it with `tags/event`; I need to check something in Xranklin as the _reason_ why this is happening may be that `cur_lc` does not get reset properly after adding tags; I'll check.
> 
> In any case if you do this:
> 
> ```julia
> function hfun_list_posts(t::String)
>     dir = dirname(cur_lc().rpath)
> 
>     startswith(dir, "tags") && return ""
>    # then rest of your function as you had it
> ```
> 
> things look like they work fine.

It seems that the current solution fails to list all posts having common tag  upon clicking on a tag.

**Comment by tlienart** [comment]
I appreciate that this might be frustrating and there may very well be bugs for me to fix but it's very hard to work with that kind of message short of just cloning your repo and trying to reproduce all your work. 

If you don't mind it would help to close this issue and open follow up issues that are more targeted. It seems that:

1. you have an issue with tags
2. there was an issue with `hfun_list_posts` being fired in the wrong context which was addressed for now with the `startswith(..)`
3. an imprecise feature request to have `{{ispage}}` figure out the type of page --> this should not be handled by `ispage`, it should be handled by you coding a `hfun_if_is_list_posts_page` and having your specific logic injecting whatever  needs to be injected if the directory meets your own constraints. 

So it seems that (1) is your remaining issue, to help you with it, it would help a lot if you first verified that the `__site/tags/` folder are appropriately filled upon site generation. I.e. do `serve(clear=true, single=true)` then go to `__site/tags/` and check that there's everything there you might expect. If not, then that's the issue. If so, then the issue is with your hfun. 

Each page has a `tags` field attached to its context which you can retrieve with `tags = getlvar(:tags)`. You can also get all of the tags by querying the global context and going through each of the local ones that is attached to it:

```julia
all_local_contexts = cur_gc().children_contexts
for rp in keys(all_local_contexts)
    a_local_context = all_local_contexts[rp]
    its_tags = getvar(a_local_context, :tags)
end
```

**Comment by luraess** [comment]
Thanks for your help. Transferring the remaining into more specific issues #275 #276.
